version: '3.6'
services:
  postgres:
    image: postgres:12
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
  hasura-support:
    build: ./hasura-support
    restart: always
    environment:
      PORT: 8081
      HASURA_ENGINE_ENDPOINT: http://hasura-engine:8080
      HASURA_GRAPHQL_ADMIN_SECRET: admin_secret
  hasura-engine:
    build: ./hasura-engine
    ports:
    - "8080:8080"
    depends_on:
    - "postgres"
    - "hasura-support"
    restart: always
    environment:
      PORT: 8080
      DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      HASURA_GRAPHQL_ADMIN_SECRET: admin_secret
      HASURA_SUPPORT_ENDPOINT: http://hasura-support:8081
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      # TODO: what log types? enable them all everywhere
volumes:
  db_data:
