version: '3.6'
services:
  postgres:
    image: postgres:12
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
  support:
    build: ./support
    depends_on:
    - "postgres"
    restart: always
    environment:
      PORT: 8081
      DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
  engine:
    build: ./engine
    ports:
    - "8080:8080"
    depends_on:
    - "postgres"
    - "support"
    restart: always
    environment:
      PORT: 8080
      DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      HASURA_GRAPHQL_ADMIN_SECRET: admin_secret
      HASURA_GRAPHQL_AUTH_HOOK: http://support:8081/auth-hook
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
volumes:
  db_data:
